multiviews: true
#only works with https://github.com/stammy/jekyll, explained below

source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year/:month/:title
pagination: true

base_url: http://www.travisberry.com

cdn: http://static-assets.travisberry.com
#base_url: http://localhost:4000
#base_url: http://travisberry-static.s3-website-us-east-1.amazonaws.com
description: "Travis Berry's blog about all thing video production and web design."
root_desc: "Travis Berry's blog about all thing video production and web design."

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb', 'CNAME', 'push', 'gemfile', 'Gemfile.lock', '_assets.yml']